/**
 * Flowable BPMN moddle extension.
 *
 * The descriptor contains Flowable Engine 6.8.1 extensions used by this modeler.
 */
const flowableDescriptor = {
  name: 'Flowable',
  uri: 'http://flowable.org/bpmn',
  prefix: 'flowable',
  xml: {
    tagAlias: 'lowerCase',
  },
  associations: [],
  types: [
    {
      name: 'Process',
      isAbstract: true,
      extends: ['bpmn:Process'],
      properties: [
        { name: 'candidateStarterUsers', type: 'String', isAttr: true },
        { name: 'candidateStarterGroups', type: 'String', isAttr: true },
        { name: 'isEagerExecutionFetching', type: 'Boolean', isAttr: true },
      ],
    },
    {
      name: 'AsyncCapable',
      isAbstract: true,
      extends: ['bpmn:Activity', 'bpmn:Gateway', 'bpmn:Event'],
      properties: [
        { name: 'async', type: 'Boolean', isAttr: true, default: false },
        { name: 'asyncLeave', type: 'Boolean', isAttr: true, default: false },
        { name: 'exclusive', type: 'Boolean', isAttr: true, default: true },
        { name: 'asyncLeaveExclusive', type: 'Boolean', isAttr: true, default: true },
        // Flowable 6.8.1 reads asyncAfter as an alias for asyncLeave.
        { name: 'asyncAfter', type: 'Boolean', isAttr: true, default: false },
      ],
    },
    {
      name: 'Initiator',
      isAbstract: true,
      extends: ['bpmn:StartEvent'],
      properties: [{ name: 'initiator', type: 'String', isAttr: true }],
    },
    {
      name: 'FormSupported',
      isAbstract: true,
      extends: ['bpmn:StartEvent', 'bpmn:UserTask'],
      properties: [
        { name: 'formKey', type: 'String', isAttr: true },
        { name: 'formFieldValidation', type: 'Boolean', isAttr: true },
        { name: 'sameDeployment', type: 'Boolean', isAttr: true, default: true },
      ],
    },
    {
      name: 'UserTask',
      isAbstract: true,
      extends: ['bpmn:UserTask'],
      properties: [
        { name: 'assignee', type: 'String', isAttr: true },
        { name: 'owner', type: 'String', isAttr: true },
        { name: 'candidateUsers', type: 'String', isAttr: true },
        { name: 'candidateGroups', type: 'String', isAttr: true },
        { name: 'dueDate', type: 'String', isAttr: true },
        { name: 'businessCalendarName', type: 'String', isAttr: true },
        { name: 'priority', type: 'String', isAttr: true },
        { name: 'category', type: 'String', isAttr: true },
        { name: 'taskIdVariableName', type: 'String', isAttr: true },
        { name: 'taskCompleterVariableName', type: 'String', isAttr: true },
      ],
    },
    {
      name: 'ServiceTaskLike',
      isAbstract: true,
      extends: [
        'bpmn:ServiceTask',
        'bpmn:BusinessRuleTask',
        'bpmn:SendTask',
        'bpmn:MessageEventDefinition',
      ],
      properties: [
        { name: 'class', type: 'String', isAttr: true },
        { name: 'expression', type: 'String', isAttr: true },
        { name: 'delegateExpression', type: 'String', isAttr: true },
        { name: 'resultVariable', type: 'String', isAttr: true },
        { name: 'resultVariableName', type: 'String', isAttr: true },
        { name: 'type', type: 'String', isAttr: true },
        { name: 'topic', type: 'String', isAttr: true },
        { name: 'triggerable', type: 'Boolean', isAttr: true },
        { name: 'caseDefinitionKey', type: 'String', isAttr: true },
        { name: 'caseInstanceName', type: 'String', isAttr: true },
        { name: 'businessKey', type: 'String', isAttr: true },
        { name: 'inheritBusinessKey', type: 'Boolean', isAttr: true, default: false },
        { name: 'sameDeployment', type: 'Boolean', isAttr: true, default: false },
        { name: 'fallbackToDefaultTenant', type: 'Boolean', isAttr: true, default: false },
        { name: 'idVariableName', type: 'String', isAttr: true },
        { name: 'useLocalScopeForResultVariable', type: 'Boolean', isAttr: true },
        { name: 'storeResultVariableAsTransient', type: 'Boolean', isAttr: true },
        { name: 'parallelInSameTransaction', type: 'Boolean', isAttr: true },
      ],
    },
    {
      name: 'SkipExpressionCapable',
      isAbstract: true,
      extends: ['bpmn:UserTask', 'bpmn:ServiceTask'],
      properties: [{ name: 'skipExpression', type: 'String', isAttr: true }],
    },
    {
      name: 'ScriptTask',
      isAbstract: true,
      extends: ['bpmn:ScriptTask'],
      properties: [
        { name: 'resultVariable', type: 'String', isAttr: true },
        { name: 'autoStoreVariables', type: 'Boolean', isAttr: true },
      ],
    },
    {
      name: 'CallActivity',
      isAbstract: true,
      extends: ['bpmn:CallActivity'],
      properties: [
        { name: 'calledElementType', type: 'String', isAttr: true },
        { name: 'inheritVariables', type: 'Boolean', isAttr: true, default: false },
        { name: 'inheritBusinessKey', type: 'Boolean', isAttr: true, default: false },
        { name: 'businessKey', type: 'String', isAttr: true },
        { name: 'sameDeployment', type: 'Boolean', isAttr: true, default: false },
        { name: 'fallbackToDefaultTenant', type: 'Boolean', isAttr: true, default: false },
        { name: 'processInstanceName', type: 'String', isAttr: true },
        { name: 'useLocalScopeForOutParameters', type: 'Boolean', isAttr: true, default: false },
        { name: 'completeAsync', type: 'Boolean', isAttr: true, default: false },
        { name: 'idVariableName', type: 'String', isAttr: true },
      ],
    },
    {
      name: 'MultiInstance',
      isAbstract: true,
      extends: ['bpmn:MultiInstanceLoopCharacteristics'],
      properties: [
        { name: 'collection', type: 'String', isAttr: true },
        { name: 'elementVariable', type: 'String', isAttr: true },
        { name: 'elementIndexVariable', type: 'String', isAttr: true },
        { name: 'noWaitStatesAsyncLeave', type: 'Boolean', isAttr: true, default: false },
      ],
    },
    {
      name: 'SequenceFlow',
      isAbstract: true,
      extends: ['bpmn:SequenceFlow'],
      properties: [{ name: 'skipExpression', type: 'String', isAttr: true }],
    },
    {
      name: 'ErrorEventDefinition',
      isAbstract: true,
      extends: ['bpmn:ErrorEventDefinition'],
      properties: [
        { name: 'errorVariableName', type: 'String', isAttr: true },
        { name: 'errorVariableTransient', type: 'Boolean', isAttr: true, default: false },
        { name: 'errorVariableLocalScope', type: 'Boolean', isAttr: true, default: false },
      ],
    },
    {
      name: 'Error',
      isAbstract: true,
      extends: ['bpmn:Error'],
      properties: [{ name: 'errorMessage', type: 'String', isAttr: true }],
    },
    {
      name: 'MessageEventDefinition',
      isAbstract: true,
      extends: ['bpmn:MessageEventDefinition'],
      properties: [
        { name: 'messageExpression', type: 'String', isAttr: true },
      ],
    },
    {
      name: 'SignalEventDefinitionExtension',
      isAbstract: true,
      extends: ['bpmn:SignalEventDefinition'],
      properties: [
        { name: 'async', type: 'Boolean', isAttr: true, default: false },
        { name: 'signalExpression', type: 'String', isAttr: true },
      ],
    },
    {
      name: 'Scope',
      extends: ['bpmn:Signal'],
      properties: [{ name: 'scope', type: 'String', isAttr: true }],
    },
    {
      name: 'ConditionalEventDefinitionExtension',
      isAbstract: true,
      extends: ['bpmn:ConditionalEventDefinition'],
      properties: [
        { name: 'variableName', type: 'String', isAttr: true },
        { name: 'variableEvents', type: 'String', isAttr: true },
      ],
    },
    {
      name: 'TimerEventDefinitionExtension',
      isAbstract: true,
      extends: ['bpmn:TimerEventDefinition'],
      properties: [{ name: 'businessCalendarName', type: 'String', isAttr: true }],
    },
    {
      name: 'TimerCycleExpressionExtension',
      isAbstract: true,
      extends: ['bpmn:Expression'],
      properties: [{ name: 'endDate', type: 'String', isAttr: true }],
    },
    {
      name: 'InOutBinding',
      superClass: ['Element'],
      isAbstract: true,
      properties: [
        { name: 'source', type: 'String', isAttr: true },
        { name: 'sourceExpression', type: 'String', isAttr: true },
        { name: 'target', type: 'String', isAttr: true },
        { name: 'targetExpression', type: 'String', isAttr: true },
        { name: 'variables', type: 'String', isAttr: true },
        { name: 'businessKey', type: 'String', isAttr: true },
        { name: 'local', type: 'Boolean', isAttr: true, default: false },
        { name: 'transient', type: 'Boolean', isAttr: true, default: false },
      ],
    },
    {
      name: 'In',
      superClass: ['InOutBinding'],
      meta: { allowedIn: ['bpmn:CallActivity', 'bpmn:ServiceTask'] },
    },
    {
      name: 'Out',
      superClass: ['InOutBinding'],
      meta: { allowedIn: ['bpmn:CallActivity', 'bpmn:ServiceTask'] },
    },
    {
      name: 'Properties',
      superClass: ['Element'],
      meta: { allowedIn: ['*'] },
      properties: [{ name: 'values', type: 'Property', isMany: true }],
    },
    {
      name: 'Property',
      superClass: ['Element'],
      properties: [
        { name: 'id', type: 'String', isAttr: true },
        { name: 'name', type: 'String', isAttr: true },
        { name: 'value', type: 'String', isAttr: true },
      ],
    },
    {
      name: 'MapException',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:Activity'] },
      properties: [
        { name: 'errorCode', type: 'String', isAttr: true },
        { name: 'includeChildExceptions', type: 'Boolean', isAttr: true, default: false },
        { name: 'rootCause', type: 'String', isAttr: true },
        { name: 'class', type: 'String', isBody: true },
      ],
    },
    {
      name: 'ExecutionListener',
      superClass: ['Element'],
      meta: { allowedIn: ['*'] },
      properties: [
        { name: 'event', type: 'String', isAttr: true },
        { name: 'class', type: 'String', isAttr: true },
        { name: 'expression', type: 'String', isAttr: true },
        { name: 'delegateExpression', type: 'String', isAttr: true },
        { name: 'type', type: 'String', isAttr: true },
        { name: 'onTransaction', type: 'String', isAttr: true },
        { name: 'customPropertiesResolverClass', type: 'String', isAttr: true },
        { name: 'customPropertiesResolverExpression', type: 'String', isAttr: true },
        { name: 'customPropertiesResolverDelegateExpression', type: 'String', isAttr: true },
        { name: 'script', type: 'Script' },
        { name: 'fields', type: 'Field', isMany: true },
      ],
    },
    {
      name: 'TaskListener',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:UserTask'] },
      properties: [
        { name: 'event', type: 'String', isAttr: true },
        { name: 'class', type: 'String', isAttr: true },
        { name: 'expression', type: 'String', isAttr: true },
        { name: 'delegateExpression', type: 'String', isAttr: true },
        { name: 'type', type: 'String', isAttr: true },
        { name: 'onTransaction', type: 'String', isAttr: true },
        { name: 'customPropertiesResolverClass', type: 'String', isAttr: true },
        { name: 'customPropertiesResolverExpression', type: 'String', isAttr: true },
        { name: 'customPropertiesResolverDelegateExpression', type: 'String', isAttr: true },
        { name: 'script', type: 'Script' },
        { name: 'fields', type: 'Field', isMany: true },
      ],
    },
    {
      name: 'Field',
      superClass: ['Element'],
      properties: [
        { name: 'name', type: 'String', isAttr: true },
        { name: 'stringValue', type: 'String', isAttr: true },
        { name: 'expression', type: 'String' },
        { name: 'string', type: 'String' },
      ],
    },
    {
      name: 'Script',
      superClass: ['Element'],
      properties: [
        { name: 'language', type: 'String', isAttr: true },
        { name: 'resultVariable', type: 'String', isAttr: true },
        { name: 'value', type: 'String', isBody: true },
      ],
    },
    {
      name: 'CustomResourceAssignmentExpression',
      isAbstract: true,
      extends: ['bpmn:ResourceAssignmentExpression'],
      properties: [{ name: 'bpmn:formalExpression', type: 'bpmn:FormalExpression' }],
    },
    {
      name: 'CustomResource',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:UserTask'] },
      properties: [
        { name: 'name', type: 'String', isAttr: true },
        {
          name: 'resourceAssignmentExpression',
          type: 'bpmn:ResourceAssignmentExpression',
        },
      ],
    },
    {
      name: 'FormProperty',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:StartEvent', 'bpmn:UserTask'] },
      properties: [
        { name: 'id', type: 'String', isAttr: true },
        { name: 'name', type: 'String', isAttr: true },
        { name: 'type', type: 'String', isAttr: true },
        { name: 'variable', type: 'String', isAttr: true },
        { name: 'expression', type: 'String', isAttr: true },
        { name: 'default', type: 'String', isAttr: true },
        { name: 'datePattern', type: 'String', isAttr: true },
        { name: 'readable', type: 'Boolean', isAttr: true, default: true },
        { name: 'writable', type: 'Boolean', isAttr: true, default: true },
        { name: 'required', type: 'Boolean', isAttr: true, default: false },
        { name: 'values', type: 'Value', isMany: true },
      ],
    },
    {
      name: 'FormData',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:StartEvent', 'bpmn:UserTask'] },
      properties: [
        { name: 'fields', type: 'FormField', isMany: true },
        { name: 'businessKey', type: 'String', isAttr: true },
      ],
    },
    {
      name: 'FormField',
      superClass: ['Element'],
      properties: [
        { name: 'id', type: 'String', isAttr: true },
        { name: 'label', type: 'String', isAttr: true },
        { name: 'type', type: 'String', isAttr: true },
        { name: 'datePattern', type: 'String', isAttr: true },
        { name: 'defaultValue', type: 'String', isAttr: true },
        { name: 'properties', type: 'Properties' },
        { name: 'validation', type: 'Validation' },
        { name: 'values', type: 'Value', isMany: true },
      ],
    },
    {
      name: 'Validation',
      superClass: ['Element'],
      properties: [{ name: 'constraints', type: 'Constraint', isMany: true }],
    },
    {
      name: 'Constraint',
      superClass: ['Element'],
      properties: [
        { name: 'name', type: 'String', isAttr: true },
        { name: 'config', type: 'String', isAttr: true },
      ],
    },
    {
      name: 'Value',
      superClass: ['Element'],
      properties: [
        { name: 'id', type: 'String', isAttr: true },
        { name: 'name', type: 'String', isAttr: true },
      ],
    },
    {
      name: 'FailedJobRetryTimeCycle',
      superClass: ['Element'],
      properties: [{ name: 'body', type: 'String', isBody: true }],
    },
    {
      name: 'JobCategory',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:FlowNode'] },
      properties: [{ name: 'body', type: 'String', isBody: true }],
    },
    {
      name: 'EventListener',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:Process'] },
      properties: [
        { name: 'events', type: 'String', isAttr: true },
        { name: 'entityType', type: 'String', isAttr: true },
        { name: 'class', type: 'String', isAttr: true },
        { name: 'delegateExpression', type: 'String', isAttr: true },
        { name: 'throwEvent', type: 'String', isAttr: true },
        { name: 'signalName', type: 'String', isAttr: true },
        { name: 'messageName', type: 'String', isAttr: true },
        { name: 'errorCode', type: 'String', isAttr: true },
        { name: 'onTransaction', type: 'String', isAttr: true },
      ],
    },
    {
      name: 'VariableListenerEventDefinition',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:Event'] },
      properties: [
        { name: 'variableName', type: 'String', isAttr: true },
        { name: 'variableChangeType', type: 'String', isAttr: true },
      ],
    },
    {
      name: 'HistoryLevel',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:Process'] },
      properties: [{ name: 'body', type: 'String', isBody: true }],
    },
    {
      name: 'IncludeInHistory',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:FlowElement'] },
      properties: [{ name: 'body', type: 'String', isBody: true }],
    },
    {
      name: 'EventType',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:Event', 'bpmn:ReceiveTask', 'bpmn:ServiceTask'] },
      properties: [{ name: 'body', type: 'String', isBody: true }],
    },
    {
      name: 'EventName',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:Event', 'bpmn:ReceiveTask', 'bpmn:ServiceTask'] },
      properties: [{ name: 'body', type: 'String', isBody: true }],
    },
    {
      name: 'EventCorrelationParameter',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:Event', 'bpmn:ReceiveTask'] },
      properties: [
        { name: 'name', type: 'String', isAttr: true },
        { name: 'type', type: 'String', isAttr: true },
        { name: 'value', type: 'String', isAttr: true },
      ],
    },
    {
      name: 'EventInParameter',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:ServiceTask'] },
      properties: [
        { name: 'source', type: 'String', isAttr: true },
        { name: 'sourceExpression', type: 'String', isAttr: true },
        { name: 'sourceType', type: 'String', isAttr: true },
        { name: 'target', type: 'String', isAttr: true },
        { name: 'targetType', type: 'String', isAttr: true },
        { name: 'transient', type: 'Boolean', isAttr: true, default: false },
      ],
    },
    {
      name: 'EventOutParameter',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:Event', 'bpmn:ReceiveTask', 'bpmn:ServiceTask'] },
      properties: [
        { name: 'source', type: 'String', isAttr: true },
        { name: 'sourceExpression', type: 'String', isAttr: true },
        { name: 'sourceType', type: 'String', isAttr: true },
        { name: 'target', type: 'String', isAttr: true },
        { name: 'targetExpression', type: 'String', isAttr: true },
        { name: 'targetType', type: 'String', isAttr: true },
        { name: 'transient', type: 'Boolean', isAttr: true, default: false },
      ],
    },
    {
      name: 'TriggerEventType',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:ServiceTask'] },
      properties: [{ name: 'body', type: 'String', isBody: true }],
    },
    {
      name: 'TriggerEventName',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:ServiceTask'] },
      properties: [{ name: 'body', type: 'String', isBody: true }],
    },
    {
      name: 'TriggerEventCorrelationParameter',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:ServiceTask'] },
      properties: [
        { name: 'name', type: 'String', isAttr: true },
        { name: 'type', type: 'String', isAttr: true },
        { name: 'value', type: 'String', isAttr: true },
      ],
    },
    ...[
      'ChannelKey',
      'ChannelName',
      'ChannelType',
      'ChannelDestination',
      'SerializerType',
      'DeserializerType',
      'TriggerChannelKey',
      'TriggerChannelName',
      'TriggerChannelType',
      'TriggerChannelDestination',
      'KeyDetectionType',
      'KeyDetectionValue',
      'SystemChannel',
      'SendSynchronously',
    ].map((name) => ({
      name,
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:FlowNode'] },
      properties: [{ name: 'body', type: 'String', isBody: true }],
    })),
    {
      name: 'StartEventCorrelationConfiguration',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:StartEvent'] },
      properties: [{ name: 'body', type: 'String', isBody: true }],
    },
    {
      name: 'Collection',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:MultiInstanceLoopCharacteristics'] },
      properties: [
        { name: 'class', type: 'String', isAttr: true },
        { name: 'delegateExpression', type: 'String', isAttr: true },
        { name: 'expression', type: 'String' },
        { name: 'string', type: 'String' },
      ],
    },
    {
      name: 'VariableAggregation',
      superClass: ['Element'],
      meta: { allowedIn: ['bpmn:MultiInstanceLoopCharacteristics'] },
      properties: [
        { name: 'target', type: 'String', isAttr: true },
        { name: 'targetExpression', type: 'String', isAttr: true },
        { name: 'storeAsTransientVariable', type: 'Boolean', isAttr: true, default: false },
        { name: 'createOverviewVariable', type: 'Boolean', isAttr: true, default: false },
        { name: 'class', type: 'String', isAttr: true },
        { name: 'delegateExpression', type: 'String', isAttr: true },
        {
          name: 'bpmn:variable',
          type: 'flowable:Variable',
          isMany: true,
          xml: { serialize: 'property' },
        },
      ],
    },
    {
      name: 'Variable',
      superClass: ['Element'],
      properties: [
        { name: 'source', type: 'String', isAttr: true },
        { name: 'sourceExpression', type: 'String', isAttr: true },
        { name: 'target', type: 'String', isAttr: true },
        { name: 'targetExpression', type: 'String', isAttr: true },
      ],
    },
    {
      name: 'HttpHandler',
      isAbstract: true,
      superClass: ['Element'],
      properties: [
        { name: 'class', type: 'String', isAttr: true },
        { name: 'delegateExpression', type: 'String', isAttr: true },
        { name: 'type', type: 'String', isAttr: true },
        { name: 'script', type: 'Script' },
        { name: 'fields', type: 'Field', isMany: true },
      ],
    },
    {
      name: 'HttpRequestHandler',
      superClass: ['HttpHandler'],
      meta: { allowedIn: ['bpmn:ServiceTask'] },
    },
    {
      name: 'HttpResponseHandler',
      superClass: ['HttpHandler'],
      meta: { allowedIn: ['bpmn:ServiceTask'] },
    },
    {
      name: 'TimeDate',
      superClass: ['Element'],
      meta: {
        allowedIn: ['bpmn:BoundaryEvent', 'bpmn:TimerEventDefinition', 'bpmn:UserTask'],
      },
      properties: [{ name: 'body', type: 'String', isBody: true }],
    },
    {
      name: 'TimeDuration',
      superClass: ['Element'],
      meta: {
        allowedIn: ['bpmn:BoundaryEvent', 'bpmn:TimerEventDefinition', 'bpmn:UserTask'],
      },
      properties: [{ name: 'body', type: 'String', isBody: true }],
    },
    {
      name: 'TimeCycle',
      superClass: ['Element'],
      meta: {
        allowedIn: [
          'bpmn:BoundaryEvent',
          'bpmn:TimerEventDefinition',
          'flowable:endDate',
          'bpmn:UserTask',
        ],
      },
      properties: [
        { name: 'body', type: 'String', isBody: true },
        { name: 'endDate', type: 'String', isAttr: true },
      ],
    },
  ],
}

export default flowableDescriptor
